/**:
  ros__parameters:
    # Mass sensor
    mass_drill:
      offset: [200000.0, 200000.0, 200000.0, 200000.0]
      scale: [450.0, 450.0, 450.0, 450.0]
      alpha: 0.8
      enabled_channels: [false, true, false, false]

    mass_container:
      offset: [200000.0, 200000.0, 200000.0, 200000.0]
      scale: [450.0, 450.0, 450.0, 450.0]
      alpha: 0.8
      enabled_channels: [false, true, false, false]

