/**:
  ros__parameters:
    mass_drill:
      offset:
        - 200000.000000001
        - 200000.000000001
        - 200000.000000001
        - 200000.000000001
      scale: [450.0, 450.0, 450.0, 450.0]
      alpha: 0.8
      enabled_channels:
        - false
        - true
        - false
        - false
    mass_container:
      offset:
        - 1.100000023841858
        - 2.000000001
        - 3.000000001
        - 4000.000000001
      scale:
        - 0.1000000014901161
        - 0.2000000029802322
        - 0.300000011920929
        - 180654.000000001
      alpha: 1
      enabled_channels:
        - true
        - true
        - false
        - true
    potentiometer:
      min_voltages: [0.0, 0.0, 0.0, 0.0]
      max_voltages: [3.0, 3.0, 3.0, 3.0]
      min_angles: [0.0, 0.0, 0.0, 0.0]
      max_angles: [180.0, 180.0, 180.0, 180.0]
      enabled_channels: [true, true, false, false]
    servo:
      min_duty: [5.0, 5.0, 5.0, 5.0]
      max_duty: [10.0, 10.0, 10.0, 10.0]
      min_angles: [0.0, 0.0, 0.0, 0.0]
      max_angles: [180.0, 180.0, 180.0, 180.0]
    accel:
      bias:
        - 0.0
        - 0.0
        - 0.0
      transform:
        - 1.0
        - 0.0
        - 0.0
        - 0.0
        - 1.0
        - 0.0
        - 0.0
        - 0.0
        - 1.0
    gyro:
      bias:
        - 0.0
        - 0.0
        - 0.0
    mag:
      hard_iron:
        - 0.0
        - 0.0
        - 0.0
      soft_iron:
        - 1.0
        - 0.0
        - 0.0
        - 0.0
        - 1.0
        - 0.0
        - 0.0
        - 0.0
        - 1.0