roco-ros-interface:
  ros__parameters:
    # Node IDs (int)
    JETSON_NDOE_ID: 0x000
    SC1_NODE_ID:    0x100
    SC2_NODE_ID:    0x200
    HD_NODE_ID:     0x300
    NAV_NODE_ID:    0x400

    # Mass sensor calibration parameters

    # Accelerometer calibration parameters
