/**:
  ros__parameters:
    # Node IDs
    JETSON_NODE_ID: 5
    SC_CONTAINER_NODE_ID: 0x001
    SC_DRILL_NODE_ID: 0x002
    HD_NODE_ID: 0x004
    NAV_NODE_ID: 0x008
    GENERAL_NODE_ID: 0x7FF

    MAX_NUMBER_NODES: 16